version: "3"
services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:

    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
        - redis
