version: "3"
services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:

    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
